spring.application.name=nstock


spring.datasource.url=mysql-29ec15d0-nstock.l.aivencloud.com
spring.datasource.username=avnadmin
spring.datasource.password=aqui va la contraseña
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
